### ISSUE TITLE
Laminas\Console dependency

### ISSUE THREAD

**Issue by bfoosness** [laminas-api-tools/api-tools-content-negotiation#20]
https://github.com/laminas-api-tools/api-tools-content-negotiation/blob/4603d6c3657b3ce12e6579663083b0d2dc35822a/src/Factory/RequestFactory.php#L32

https://github.com/laminas/laminas-console is now deprecated. Would it make sense to always return `HttpRequest` if the console tooling is not present? I've tried this locally and it appears to work, but I admittedly don't fully understand the implications of doing so.

We have a use case where our Laminas application can be run from the command line (meaning `PHP_SAPI === 'cli'` is true), but our application doesn't need laminas-console. This line, however, means that we can't remove laminas-console as a dependency.

**Comment by pavkatar** [comment]
Any updates on the Laminas/Cli implementation?

**Comment by bfoosness** [comment]
@weierophinney, does this seem reasonable, or is there a better alternative?

**Comment by weierophinney** [comment]
laminas/cli has been stable for quite some time now, and I'm even currently [working on an update to mezzio/mezzio-tooling to migrate it to laminas/cli](https://github.com/mezzio/mezzio-tooling/milestone/4).

We can llikely remove this dependency for a new minor version; the problem is that the versions of laminas-mvc that Laminas API Tools target still have a dependency on laminas-console, IIRC, so it may not actually go away entirely.

Feel free to create a pull request, though - we can at least start addressing it here.

**Comment by bfoosness** [comment]
Right, it may not, though at least in our project's composer.lock, I don't see any hard requirements on laminas-console.

To clarify, a simple pull request to always return `HttpRequest` if the console tooling is not present, or are you thinking a transition to laminas/cli is necessary here as well?

**Comment by weierophinney** [comment]
@bfoosness No need to use laminas-cli here. Just return HttpRequest.

The laminas-mvc-console functionality existed to allow exposing controller actions to the console. We have since realized this is a pretty horrible pattern, and that CLI functionality should be separate from the MVC, as they have completely different needs. The functionality exposed by the author of this issue is an artifact from working with laminas-mvc-console. I'm not entirely sure why the "Request" service is being wired in this module, TBH - laminas-mvc does that already, and this just duplicates what laminas-mvc was doing. I suspect it only existed for testing purposes within this package.

**Comment by bfoosness** [comment]
Thank you, @weierophinney. That all makes sense. #22 is up!

**Comment by bfoosness** [comment]
Some of the build checks are failing due to ` [Composer\Downloader\TransportException] Could not authenticate against github.com`, but in looking at previous builds this seems like a recurring/intermittent issue.

**Comment by dstockto** [comment]
Is there anything I can do to help get this in? I've moved all my other console apps to the new stuff, but after removing laminas/laminas-console and laminas/laminas-mvc-console then *some* of the CLI tools fail due to content-negotiation trying to return a ConsoleRequest. I think this is one of the last things I need to be able to upgrade/remove to be able to go to PHP 8.

Thank you

**Comment by bfoosness** [comment]
@weierophinney: Is there anything more I can do to help move this forward? That PR is up for review, and the failing build seems to be unrelated.
